# Generated by Django 4.1.6 on 2023-02-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelTimeModels',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('start_time_int', models.FloatField(default=0.0)),
                ('start_time_str', models.CharField(max_length=50)),
                ('end_time_int', models.FloatField(default=0.0)),
                ('end_time_str', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorProgramModels',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('date_int', models.FloatField(default=0.0)),
                ('date_str', models.CharField(default='-', max_length=50)),
                ('program_turn', models.CharField(choices=[('m', 'morning'), ('a', 'afternoon')], default='m', max_length=1)),
            ],
        ),
    ]
