# Generated by Django 4.1.6 on 2023-02-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('Admin', '0002_rename_canceltimemodels_canceltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprogram',
            name='operator',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.user'),
        ),
        migrations.AddField(
            model_name='operatorprogram',
            name='operator_user_name',
            field=models.CharField(default='UnKnow', max_length=20, null=True),
        ),
    ]
