# Generated by Django 4.1.6 on 2023-02-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_operatorprogram_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorprogram',
            old_name='operator_user_name',
            new_name='operator_name',
        ),
    ]
