# Generated by Django 4.1.6 on 2023-02-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('national_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('house_number', models.CharField(max_length=15)),
                ('drug_hist', models.BooleanField(default=False)),
                ('decease_hist', models.BooleanField(default=False)),
                ('doctor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='user', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='user', max_length=50)),
                ('last_name', models.CharField(default='user', max_length=50)),
                ('phone_number', models.CharField(default='0989121112244', max_length=13)),
                ('password', models.CharField(default='****', max_length=50)),
                ('user_type', models.CharField(choices=[('a', 'admin'), ('r', 'reception'), ('o', 'operator'), ('c', 'customer')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_code', models.CharField(default='****', max_length=128, primary_key=True, serialize=False)),
                ('token_create_time_int', models.FloatField(default=0.0)),
                ('token_create_time_str', models.CharField(default='-', max_length=25)),
                ('token_expire_time_int', models.FloatField(default=0.0)),
                ('token_expire_time_str', models.CharField(default='-', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('code', models.CharField(default='****', max_length=5, primary_key=True, serialize=False)),
                ('expire_time', models.FloatField(default=0.0)),
                ('proved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEnterExit',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('enter_time_int', models.FloatField(default=0.0)),
                ('enter_time_str', models.CharField(default='-', max_length=25)),
                ('exit_time_int', models.FloatField(default=0.0)),
                ('exit_time_str', models.CharField(default='-', max_length=25)),
                ('exited', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('create_time_int', models.FloatField(default=0.0)),
                ('create_time_str', models.CharField(default='-', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
        ),
    ]
