# Generated by Django 4.1.6 on 2023-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='code_generate',
            field=models.CharField(default='****', max_length=8),
        ),
    ]
