# Generated by Django 4.1.6 on 2023-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_forgotpassword_code_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
