# Generated by Django 4.1.6 on 2023-02-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_customer_charge_alter_forgotpassword_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeenterexit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.user'),
        ),
    ]
