# Generated by Django 4.1.6 on 2023-02-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('payment_time_int', models.FloatField(default=0.0)),
                ('payment_time_str', models.CharField(default='-', max_length=25)),
                ('payment_type', models.CharField(choices=[('ca', 'cash'), ('cr', 'credit card'), ('ch', 'check')], max_length=2)),
            ],
        ),
    ]
