# Generated by Django 4.1.6 on 2023-02-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Payment', '0001_initial'),
        ('Reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reserve.reserve'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.user'),
        ),
    ]
