# Generated by Django 4.1.6 on 2023-05-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaserArea',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('current_price', models.FloatField(default=0.0)),
                ('deadline_reset', models.IntegerField(default=30)),
                ('status', models.BooleanField(default=True)),
                ('operate_time', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='LaserAreaInformation',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('start_time_int', models.FloatField(default=0.0)),
                ('start_time_str', models.CharField(default='-', max_length=25)),
                ('end_time_int', models.FloatField(default=0.0)),
                ('end_time_str', models.CharField(default='-', max_length=25)),
                ('operate_time', models.IntegerField(default=5)),
                ('laser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LazerApp.laserarea')),
            ],
        ),
    ]
